FROM python:3.9-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y curl build-essential gcc \
    && curl -sSL https://install.python-poetry.org | python3 - \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="${PATH}:/root/.local/bin"

COPY pyproject.toml poetry.lock* /app/

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

RUN pip install scikit-learn==1.0
