jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify your Python version here

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies with Poetry
        run: |
          poetry install

      - name: Compile Kubeflow Pipeline to JSON
        run: |
          poetry run python mlpipeline.py --compile-json

      - name: Deploy Pipeline to Vertex AI
        env:  # Set the environment variables for the gcloud command
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PIPELINE_ROOT: ${{ secrets.PIPELINE_ROOT }}
          REGION: ${{ secrets.REGION }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          # First authenticate with gcloud using the service account key
          echo "$GOOGLE_APPLICATION_CREDENTIALS" | gcloud auth activate-service-account --key-file=-
          # Then deploy the pipeline to Vertex AI
          gcloud ai pipelines create \
            --region=$REGION \
            --pipeline-root=$PIPELINE_ROOT \
            --project=$PROJECT_ID \
            --display-name=mlplatform-pipeline \
            --template-path=./mlplatform_pipeline.json
