name: Deploy to Vertex AI

on:
  push:
    branches:
      - main
  workflow_dispatch: 

env:
  PIPELINE_ROOT: ${{ secrets.PIPELINE_ROOT }}
  CONTAINER_IMAGE: ${{ secrets.CONTAINER_IMAGE }}
  SERVING_IMAGE: ${{ secrets.SERVING_IMAGE }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  ARTIFACT_REPO: ${{ secrets.ARTIFACT_REPO }}
  GCS_URL: ${{ secrets.GCS_URL }}
  TRAIN_RATIO: ${{ secrets.TRAIN_RATIO }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  REGION: ${{ secrets.REGION }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.GSA_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install

      - name: Compile Kubeflow Pipeline to JSON
        run: |
          poetry run python mlpipeline.py --compile-json

      - name: Deploy Pipeline to Vertex AI
        run: |
          gcloud ai pipelines create \
            --region=${{ env.REGION }} \
            --pipeline-root=${{ env.PIPELINE_ROOT }} \
            --project=${{ env.PROJECT_ID }} \
            --display-name=mlplatform-pipeline \
            --template-path=./mlplatform_pipeline.json